services:
  nginx:
   image: nginx
   volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
   ports:
    - 80:80
   depends_on:
   - webapp
  redis:
   image: redis
   ports:
   - 6379:6379
   depends_on:
   - mongo 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
    - mongo
  mongo:
   image: mongo
   restart: always
   environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
   volumes:
    - mongo-db:/data/db
  webapp:
   deploy:
    replicas: 4
    update_config:
     parallelism: 2
     delay: 30s
    restart_policy:
     condition: on_failure
     delay: 5s 


   image: osamazazatestcrew/osamadockerimage
   container_name: mySpecialContainer1
   working_dir: /app
   env_file:
   - ./.env
   ports:
   - "4000:4000"
   depends_on:
   - redis

volumes: 
 mongo-db: